app = 'bachelors-ton-wallet-telegram-bot'
primary_region = 'waw'

[env]
  TELEGRAM_ENVIRONMENT = 'production'
  TELEGRAM_MINI_APP_URL = 'https://ton-wallet-client-main.shabashab.dev'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

