name: Deploy Server Index Production

on:
  push:
    branches:
      - main
    paths:
      - 'apps/server-index/**'
      - 'infra/server-index/**'
      - '.github/workflows/deploy-server-index.yml'

jobs:
  deploy:
    name: Deploy production server-index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c infra/server-index/fly.toml  --dockerfile infra/server-index/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
